<?php

/**
 * @file
 * IKS content enhancment javascript module file.
 */

function iksce_js_init() {

  // Enable to test annotate.js
  //drupal_add_library('iksce_js', 'vie.annotate');
  //drupal_add_js(drupal_get_path('module', 'iksce_js') . '/iksce.js');

  // Does not work because of missing jquery ui tooltip - included with 1.9
  //drupal_add_library('iksce_js', 'vie.entitypreview');
  //drupal_add_js(drupal_get_path('module', 'iksce_js') . '/entitypreview.js');
}

/**
 * Implements hook_library().
 */
function iksce_js_library() {

  $libraries['rdfquery'] = array(
    'title' => 'rdfquery',
    'website' => 'http://code.google.com/p/rdfquery/',
    'version' => '1.0',
    'js' => array(
      libraries_get_path('rdfquery') . '/jquery.rdfquery.rules-1.0.js' => array(),
    ),
  );

  $libraries['vie'] = array(
    'title' => 'VIE.js',
    'website' => 'http://viejs.org/',
    'version' => '2.0.0',
    'js' => array(
      libraries_get_path('vie') . '/vie-2.0.0.debug.js' => array(),
    ),
    'dependencies' => array(
      array('backbone_library' , 'backbone'),
      array('iksce_js' , 'rdfquery'),
    ),
  );

  $libraries['vie.annotate'] = array(
    'title' => 'vie.annotate.js',
    'website' => 'https://github.com/szabyg/annotate.js',
    'version' => 'dev',
    'js' => array(
      libraries_get_path('vie') . '/annotate.js' => array(),
    ),
    'css' => array(
      drupal_get_path('module', 'iksce_js') . '/annotate.css' => array(),
    ),
    'dependencies' => array(
      array('iksce_js' , 'vie'),
      array('system', 'ui.dialog'),
      array('system', 'ui.autocomplete'),
    ),
  );

  $libraries['vie.entitypreview'] = array(
    'title' => 'vie.entitypreview.js',
    'website' => 'https://github.com/szabyg/vie.entitypreview',
    'version' => 'dev',
    'js' => array(
      libraries_get_path('vie') . '/vie.entitypreview.js' => array(),
    ),
    'dependencies' => array(
      array('iksce_js' , 'vie'),
    ),
  );
  $libraries['vie.autocomplete'] = array(
    'title' => 'vie.autocomplete.js',
    'website' => 'https://github.com/szabyg/VIE.autocomplete',
    'version' => 'dev',
    'js' => array(
      libraries_get_path('vie') . '/vie.autocomplete.js' => array(),
    ),
    'dependencies' => array(
      array('iksce_js' , 'vie'),
      array('system', 'ui.autocomplete'),
      array('iksce_js', 'vie.entitypreview'),
    ),
  );

  return $libraries;
}