<?php

/**
 * @file
 * IKS content enhancment javascript module file.
 */

function iksce_js_init() {

  // Enable to test annotate.js
  drupal_add_library('iksce_js', 'vie.annotate');
  // Let this run after wysiwyg
  drupal_add_js(drupal_get_path('module', 'iksce_js') . '/iksce_annotate.js', array('defer' => TRUE));
  drupal_add_css(drupal_get_path('module', 'iksce_js') . '/iksce_annotate.css');

  // Does not work because of missing jquery ui tooltip - included with 1.9
  //drupal_add_library('iksce_js', 'vie.entitypreview');
  //drupal_add_js(drupal_get_path('module', 'iksce_js') . '/entitypreview.js');
}

/**
 * Returns the configuration for VIE.js
 */
function iksce_vie_stanbol_config() {
  // This are the settings as passed to "new vie.StanbolService" in js.
  return array(
    'url' => 'http://localhost:8080',
    'proxyDisabled' => TRUE,
  );
}

/**
 * Implements hook_library().
 */
function iksce_js_library() {

  $libraries['rdfquery'] = array(
    'title' => 'rdfquery',
    'website' => 'http://code.google.com/p/rdfquery/',
    'version' => '1.0',
    'js' => array(
      libraries_get_path('rdfquery') . '/jquery.rdfquery.rules-1.0.js' => array(),
    ),
  );

  $libraries['vie'] = array(
    'title' => 'VIE.js',
    'website' => 'http://viejs.org/',
    'version' => '2.0.0',
    'js' => array(
      libraries_get_path('vie') . '/vie-2.0.0.debug.js' => array(),
      array('type' => 'setting', 'data' => array('iksce' => array('stanbol' => iksce_vie_stanbol_config()))),
    ),
    'dependencies' => array(
      array('backbone_library' , 'backbone'),
      array('iksce_js' , 'rdfquery'),
    ),
  );

  $libraries['vie.annotate'] = array(
    'title' => 'vie.annotate.js',
    'website' => 'https://github.com/szabyg/annotate.js',
    'version' => 'dev',
    'js' => array(
      libraries_get_path('vie') . '/annotate.js' => array(),
    ),
    'dependencies' => array(
      array('iksce_js' , 'vie'),
      array('system', 'ui.dialog'),
      array('system', 'ui.autocomplete'),
    ),
  );

  $libraries['vie.entitypreview'] = array(
    'title' => 'vie.entitypreview.js',
    'website' => 'https://github.com/szabyg/vie.entitypreview',
    'version' => 'dev',
    'js' => array(
      libraries_get_path('vie') . '/vie.entitypreview.js' => array(),
    ),
    'dependencies' => array(
      array('iksce_js' , 'vie'),
    ),
  );
  $libraries['vie.autocomplete'] = array(
    'title' => 'vie.autocomplete.js',
    'website' => 'https://github.com/szabyg/VIE.autocomplete',
    'version' => 'dev',
    'js' => array(
      libraries_get_path('vie') . '/vie.autocomplete.js' => array(),
    ),
    'dependencies' => array(
      array('iksce_js' , 'vie'),
      array('system', 'ui.autocomplete'),
      array('iksce_js', 'vie.entitypreview'),
    ),
  );

  return $libraries;
}